"""add category_groups table and group_id to budget_categories

Revision ID: 42e1f14b9fd6
Revises: 
Create Date: 2026-03-01 15:11:38.933217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42e1f14b9fd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    with op.batch_alter_table('budget_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'category_groups', ['group_id'], ['id'])

    with op.batch_alter_table('category_groups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('category_groups_name_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_groups', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('category_groups_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('budget_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('group_id')

    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['category_groups.id'], name=op.f('categories_group_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey'))
    )
    # ### end Alembic commands ###
